apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: yy3og2l4q-python 
  janus-idp.io/tekton: yy3og2l4q-python
  backstage.io/kubernetes-id: yy3og2l4q-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yy3og2l4q-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml