apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yy3og2l4q-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yy3og2l4q-python 
  name: yy3og2l4q-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yy3og2l4q-python 
